added the dynamic variable

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -91,11 +91,12 @@ jobs:
         id: get_ip
         run: |
             VM_PRIVATE_IP=$(terraform output -raw vm_private_ip || echo "no-ip")
-            if [[ "$VM_PRIVATE_IP" == "no-ip" ]]; then
-            echo "Failed to fetch VM private IP."
-            exit 1
-            fi
-            echo "Private IP fetched: $VM_PRIVATE_IP"
+            echo "VM_PRIVATE_IP=${VM_PRIVATE_IP}" >> $GITHUB_ENV
+            # if [[ "$VM_PRIVATE_IP" == "no-ip" ]]; then
+            #    echo "Failed to fetch VM private IP."
+            #    exit 1
+            # fi
+            # echo "Private IP fetched: $VM_PRIVATE_IP"
         env:
           ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
           ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
