added the invenroty file and update

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -90,25 +90,19 @@ jobs:
       - name: Get private IP address
         id: get_ip
         run: |
-            echo "Fetching the private IP address..."
-            vm_private_ip=$(terraform output -json vm_private_ip  | jq -r .value)
-            echo "vm_private_ip =${vm_private_ip}" >> $GITHUB_ENV
-  
-
-      
-      - name: Install Ansible
-        run: |
-          sudo apt update
-          sudo apt install -y ansible jq
+            VM_PRIVATE_IP=$(terraform output -raw vm_private_ip || echo "no-ip")
+            if [[ "$VM_PRIVATE_IP" == "no-ip" ]]; then
+            echo "Failed to fetch VM private IP."
+            exit 1
+            fi
+            echo "Private IP fetched: $VM_PRIVATE_IP"
     
       - name: Create Dynamic Inventory
         run: |
-          VM_PRIVATE_IP=$(terraform output -raw vm_private_ip || echo "no-ip")
-          if [[ "$VM_PRIVATE_IP" == "no-ip" ]]; then
-          echo "Failed to fetch VM private IP."
-          exit 1
-          fi
-          echo "Private IP fetched: $VM_PRIVATE_IP"
+          echo "[windows]" > inventory.ini
+          echo "my_windows_vm ansible_host=${{ env.vm_private_ip  }} ansible_user=adminuser  ansible_password="Welcome#2024" ansible_connection=winrm ansible_port=5985 ansible_winrm_server_cert_validation=ignore >> inventory.ini
+          echo "Dynamic inventory created:"
+          cat inventory.ini  # Display the inventory for verification
     
       - name: Run Ansible Playbook
         run: |
