added task capture the pvt ip of vm

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -85,6 +85,20 @@ jobs:
       - name: Make create_inventory.sh executable
         run: chmod +x ./create_inventory.sh
 
+      - name: Get private IP address
+        id: get_ip
+        run: |
+            VM_PRIVATE_IP=$(terraform output -raw vm_private_ip || echo "no-ip")
+            if [[ "$VM_PRIVATE_IP" == "no-ip" ]]; then
+            echo "Failed to fetch VM private IP."
+            exit 1
+            fi
+            echo "Private IP fetched: $VM_PRIVATE_IP"  
+        env:
+          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}    
+          
       - name: Generate Ansible Inventory
         run: ./create_inventory.sh
         working-directory: '${{github.workspace}}/terraform-poc'
